name: r-gluonts
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - mxnet==1.9.1
    - gluonts==0.8.0
    # - numpy==1.16.6
    # - numpy==1.17.2
    - numpy
    - pandas==1.0.5
    - pathlib==1.0.1
    - ujson==4.0.2
    # - torch
    # - pytorch-lightning
